config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'pages#home'
  resources :userreads
  get 'sessions/new'
  get 'comics/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/read', to: 'book#read'
  post 'comics/create'
  get'/login',to: 'sessions#new'
  delete '/logout', to:'sessions#destroy'
  post'sessions/create'
  resources :comics
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

end

app/models/userread.rb
class Userread < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def logged_in?
       !session[:user_id].nil?
   end

   private

   def current_user
       @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
   end
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def read
    @comics=Comic.all
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController

  before_action :login_required

  def new
  end

  def create
   comic = Comic.new(comic_params)
   comic.save
   flash[:success] = "#{comic.title}を追加しました"
   redirect_to root_path
 end

 def edit
  @comic = Comic.find(params[:id])
 end

 def update
   @comic = Comic.find(params[:id])
   if @comic.update_attributes(comic_params)
     flash[:success] = "漫画の更新に成功しました"
     redirect_to read_path
   else
     render 'edit'
   end
 end

 def destroy
   Comic.find(params[:id]).destroy
   flash[:success]="漫画情報を削除しました"
   redirect_to read_path
 end

 private

 def comic_params
   params.require(:comic).permit(:title, :author)
 end


 def login_required
   redirect_to login_path unless current_user
 end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
   user = User.find_by(email: session_params[:email])

   if user&.authenticate(session_params[:password])
       session[:user_id] = user.id
       flash[:success] = 'ログインしました'
       redirect_to root_path
   else
       flash[:danger] = 'ログインに失敗しました'
       render :new
   end
  end

  def destroy
   session.delete(:user_id)
   flash[:success] = 'ログアウトしました'
   redirect_to root_path
 end
 
  private

  def session_params
    params.require(:session).permit(:email, :password)
  end




end

app/controllers/userreads_controller.rb
class UserreadsController < ApplicationController
  before_action :set_userread, only: [:show, :edit, :update, :destroy]

  # GET /userreads
  # GET /userreads.json
  def index
    @userreads = Userread.all
    @users=User.all
    @comics=Comic.all
  end

  # GET /userreads/1
  # GET /userreads/1.json
  def show
    @users=User.all
    @comics=Comic.all
  end

  # GET /userreads/new
  def new
    @userread = Userread.new
    @users=User.all
    @comics=Comic.all
  end

  # GET /userreads/1/edit
  def edit
    @users=User.all
    @comics=Comic.all
  end

  # POST /userreads
  # POST /userreads.json
  def create
    @userread = Userread.new(userread_params)

    respond_to do |format|
      if @userread.save
        format.html { redirect_to @userread, notice: 'Userread was successfully created.' }
        format.json { render :show, status: :created, location: @userread }
      else
        format.html { render :new }
        format.json { render json: @userread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userreads/1
  # PATCH/PUT /userreads/1.json
  def update
    respond_to do |format|
      if @userread.update(userread_params)
        format.html { redirect_to @userread, notice: 'Userread was successfully updated.' }
        format.json { render :show, status: :ok, location: @userread }
      else
        format.html { render :edit }
        format.json { render json: @userread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userreads/1
  # DELETE /userreads/1.json
  def destroy
    @userread.destroy
    respond_to do |format|
      format.html { redirect_to userreads_url, notice: 'Userread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userread
      @userread = Userread.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userread_params
      params.require(:userread).permit(:comic_id, :user_id, :vol)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]

 def index
   @users = User.all
 end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Bookshelfアカウントの作成に成功しました。"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
   @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success]="アカウントを削除しました"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

  # beforeアクション

    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      # redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Bookshelf App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end


  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/userreads_helper.rb
module UserreadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book/read.html.erb
<%= provide(:title, "読んだ漫画") %>
<div class="center jumbotron">
<h1>登録漫画一覧</h1>
<h2>
  <ul>
<% @comics.each do |c| %>
        <li>
          <%= c.title %>(作者:<%= c.author %>)
          <%= link_to "編集",edit_comic_path(c) %>
           | <%= link_to "削除", c, method: :delete, data: {confirm: "削除してもいいですか?"} %>
        </li>
    <% end %>
  </ul>
</h2>
</div>

app/views/comics/edit.html.erb
<% provide(:title, "漫画の編集") %>
<h1>漫画の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@comic) do |f| %>

      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :author, "作者"  %>
      <%= f.text_field :author, class: 'form-control' %>

      <%= f.submit "変更", class: "btn btn-primary" %>
    <% end %>

    </div>
  </div>
</div>

app/views/comics/new.html.erb
<%= provide(:title, "漫画の追加") %>

<h1> 漫画の追加</h1>
<h2>
<%= form_with model: Comic.new, url: {action: :create}, local: true do |f| %>
<div　class="row">
  <div class="col-md-6 col-md-offset-3">
 <%= f.label :title, "作品名" %>
 <%= f.text_field :title, id: 'comic_title', class: 'form-control' %>

 <%= f.label :author, "作者" %>
 <%= f.text_field :author, id: 'comic_author', class: 'form-control' %>

 <%= f.submit "変更",class: "btn btn-primary"%>
</div>
</div>


<% end %>

</h2>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Bookshelf",   root_path %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "ホーム",   root_path %></li>
      <li><%= link_to "漫画一覧", read_path %></li>
      <li><%= link_to "全ユーザの管理", users_path%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Bookshelf", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "漫画一覧", read_path %></li>
        <% if logged_in? %>
        <li><%= link_to "漫画の追加", comics_new_path %></li>
        <li><%= link_to "マイページ", current_user %></li>
        <li><%= link_to "設定", edit_user_path(current_user) %></li>
        <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
       <% else %>
         <li><%= link_to "ログイン", login_path %></li>
       <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">

    <% flash.each do |message_type, message| %>
     <div class="alert alert-<%= message_type %>"><%= message %></div>
     <% end %>


    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Bookshelfへようこそ</h1>

  <h2>
    「あれ、あの漫画何巻まで読んだっけ・・・」<br>
    「あーこの前ちらっと読んだ漫画、名前なんだったかな？」<br>

    そんな悩みを簡単解決！！<br>
    使い方は漫画を選んで登録するだけ。<br>
    シンプルで使いやすいアプリです。
  </h2>
  <% if logged_in? %>
  <%= link_to "Bookshelfを始める！",userreads_path, class:"btn btn-lg btn-primary" %>
 <% else %>
<%= link_to "Bookshelfを始める！","users/new", class:"btn btn-lg btn-primary" %>
 <% end %>


</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/userreads/_form.html.erb
<%= form_with(model: userread, local: true) do |form| %>
  <% if userread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(userread.errors.count, "error") %> prohibited this userread from being saved:</h2>

      <ul>
      <% userread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :comic_id, "漫画"%>
    <%= form.select :comic_id,@comics.map{|c| [c.title,c.id]} %>
  </div>

  <div class="field">
    <%= form.label :user_id, "ユーザ" %>
    <%= form.select :user_id,@users.map{|u| [u.name,u.id]} %>
  </div>

  <div class="field">
    <%= form.label :vol, "巻数" %>
    <%= form.text_field :vol %>
  </div>

  <div class="actions">
    <%= form.submit "本棚にしまう" %>
  </div>
<% end %>

app/views/userreads/edit.html.erb
<% provide(:title, "編集") %>
<h1>本棚の編集</h1>

<%= render 'form', userread: @userread %>

<%= link_to 'Show', @userread %> |
<%= link_to 'Back', userreads_path %>

app/views/userreads/index.html.erb
<% provide(:title, "本棚") %>
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Comic</th>
      <th>User</th>
      <th>Vol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userreads.each do |userread| %>
      <tr>
        <td><%= @comics[userread.comic_id-1].title %></td>
        <td><%= @users[userread.user_id-1].name %></td>
        <td><%= userread.vol %></td>
        <td><%= link_to '本の詳細をみる', userread %></td>
        <td><%= link_to '編集', edit_userread_path(userread) %></td>
        <td><%= link_to '削除', userread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '本棚へ新しい本を登録する', new_userread_path %>

app/views/userreads/new.html.erb
<% provide(:title, "本棚へ登録") %>
<h1>本棚へ入れる</h1>

<%= render 'form', userread: @userread %>

<%= link_to '本棚へ', userreads_path %>

app/views/userreads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comic:</strong>
  <%= @comics[@userread.comic_id-1].title %>
</p>

<p>
  <strong>User:</strong>
  <%= @users[@userread.user_id-1].name %>
</p>

<p>
  <strong>第<%= @userread.vol %>巻</strong>
</p>

<%= link_to '編集', edit_userread_path(@userread) %> |
<%= link_to '本棚へ', userreads_path %>

app/views/users/edit.html.erb
<% provide(:title, "アカウントの編集") %>
<h1>アカウントの編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "Email"  %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード"  %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワードの確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "変更", class: "btn btn-primary" %>
    <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '登録ユーザ') %>
<h1>登録ユーザ</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      | <%= link_to "削除",user, method: :delete, data: {confirm: "削除してもいいですか?"} %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<h1>新規ユーザの登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

    <%= render 'shared/error_messages' %>

    <%= f.label :name ,"名前" %>
    <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "E-mail" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワードの確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        ID:<%= @user.email %><br>
        名前:<%= @user.name %>
      </h1>

      <h2>
        <%= link_to "本棚へ行く",userreads_path %>
    </section>
  </aside>
</div>